/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#4500d8",
        "on-background": "#1c1a25",
        "on-primary-container": "#e3dbff",
        "error": "#ba1a1a",
        "surface": "#FFFFFF",
        "surface-container-high": "#ebe6f5",
        "surface-bright": "#fdf8ff",
        "on-secondary-container": "#65000d",
        "tertiary": "#852f00",
        "outline-variant": "#c9c3da",
        "surface-container-low": "#f7f1ff",
        "subject-yellow": "#FFC043",
        "tertiary-container": "#ac4000",
        "inverse-primary": "#c9bfff",
        "on-surface-variant": "#484456",
        "surface-tint": "#5d2ffa",
        "primary": "#4900e5",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ffd8c9",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e5e0f0",
        "on-error-container": "#93000a",
        "secondary": "#b2292f",
        "secondary-fixed": "#ffdad7",
        "on-secondary-fixed": "#410005",
        "surface-dim": "#ddd8e7",
        "surface-container-highest": "#e5e0f0",
        "background": "#F4F5F7",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "inverse-surface": "#312f3a",
        "primary-container": "#6236ff",
        "on-tertiary-fixed": "#360f00",
        "subject-green": "#4CD964",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1b0063",
        "tertiary-fixed": "#ffdbcd",
        "secondary-container": "#fe6060",
        "on-secondary-fixed-variant": "#900b1b",
        "surface-container": "#f1ebfb",
        "on-tertiary-fixed-variant": "#7e2c00",
        "inverse-on-surface": "#f4eefe",
        "primary-fixed-dim": "#c9bfff",
        "on-primary": "#ffffff",
        "text-primary": "#1C1C1E",
        "on-surface": "#1c1a25",
        "primary-fixed": "#e5deff",
        "outline": "#797488",
        "text-secondary": "#7F7F8A",
        "tertiary-fixed-dim": "#ffb597",
        "secondary-fixed-dim": "#ffb3af",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "12px",
        "card-padding": "24px",
        base: "8px",
        "margin-mobile": "16px",
        "gap-md": "16px",
      },
      fontFamily: {
        "headline-xl": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-base": ["1rem", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["0.813rem", { lineHeight: "18px", fontWeight: "500" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
